# **Project Name - Travel Recommendation System**

Project Type - EDA/Classification

Contribution - Individual
member-nikita shrama

# Project Summary -

**Project Summary: Hotel Recommendation System**



This project focuses on building a Hotel Recommendation System using collaborative filtering techniques and deploying it as an interactive web application through Streamlit and ngrok. The project was developed in Google Colab and leverages Singular Value Decomposition (SVD) from the Surprise library to generate personalized hotel recommendations for users based on historical data.

**Project Outcomes:**

The project successfully implemented a collaborative filtering-based recommendation system that provides personalized hotel recommendations.
By integrating Streamlit with ngrok, the project demonstrates a practical approach to deploying data science models as interactive web applications directly from Google Colab.
The addition of filtering and sorting features further enhances the utility of the system, making it adaptable to real-world scenarios.
This project showcases the application of machine learning techniques to the travel and tourism industry, offering personalized recommendations in an accessible and user-friendly format.

#**GitHub Link -**

#**Problem Statement**

Build a recommendation model to provide hotel suggestions based on user preferences and historical data. Develop a Streamlit web application to display insights and visualizations derived from the deployed travel recommendation model, offering an interactive and user-friendly interface for data exploration.

# Let's Begin !

## Import librabries

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import random
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,classification_report, precision_recall_curve
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [ ]:
# Load the hotel data from the CSV file
hotel_path = "hotels.csv"
hotel = pd.read_csv(hotel_path)

In [ ]:
hotel.head()

,travelCode,userCode,name,place,days,price,total,date
0,0,0,Hotel A,Florianopolis (SC),4,313.02,1252.08,09/26/2019
1,2,0,Hotel K,Salvador (BH),2,263.41,526.82,10/10/2019
2,7,0,Hotel K,Salvador (BH),3,263.41,790.23,11/14/2019
3,11,0,Hotel K,Salvador (BH),4,263.41,1053.64,12/12/2019
4,13,0,Hotel A,Florianopolis (SC),1,313.02,313.02,12/26/2019

In [ ]:
hotel.shape

(40552, 8)

In [ ]:
hotel.describe()

          travelCode      userCode          days         price         total
count   40552.000000  40552.000000  40552.000000  40552.000000  40552.000000
mean    67911.794461    666.963726      2.499679    214.439554    536.229513
std     39408.199333    391.136794      1.119326     76.742305    319.331482
min         0.000000      0.000000      1.000000     60.390000     60.390000
25%     33696.750000    323.000000      1.000000    165.990000    247.620000
50%     67831.000000    658.000000      2.000000    242.880000    495.240000
75%    102211.250000   1013.000000      4.000000    263.410000    742.860000
max    135942.000000   1339.000000      4.000000    313.020000   1252.080000

In [ ]:
hotel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40552 entries, 0 to 40551
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   travelCode  40552 non-null  int64
 1   userCode    40552 non-null  int64
 2   name        40552 non-null  object
 3   place       40552 non-null  object
 4   days        40552 non-null  int64
 5   price       40552 non-null  float64
 6   total       40552 non-null  float64
 7   date        40552 non-null  object
dtypes: float64(2), int64(3), object(3)
memory usage: 2.5+ MB

In [ ]:
hotel.isnull().sum()

travelCode    0
userCode      0
name          0
place         0
days          0
price         0
total         0
date          0
dtype: int64

In [ ]:
# Handling date format inconsistencies
hotel['date'] = pd.to_datetime(hotel['date'], errors='coerce')

In [ ]:
# Encode categorical columns
label_encoder_name = LabelEncoder()
hotel['name'] = label_encoder_name.fit_transform(hotel['name'])

label_encoder_place = LabelEncoder()
hotel['place'] = label_encoder_place.fit_transform(hotel['place'])

In [ ]:
# Selecting features and target variable
X = hotel[['travelCode', 'userCode', 'days', 'price', 'total']]
y_name = hotel['name']
y_place = hotel['place']
y_price = hotel['price']

# Splitting the hotel into training and testing sets
X_train, X_test, y_name_train, y_name_test = train_test_split(X, y_name, test_size=0.2, random_state=42)
_, _, y_place_train, y_place_test = train_test_split(X, y_place, test_size=0.2, random_state=42)
_, _, y_price_train, y_price_test = train_test_split(X, y_price, test_size=0.2, random_state=42)

In [ ]:
# Train the model for hotel name prediction
model_name = RandomForestClassifier()
model_name.fit(X_train, y_name_train)

# Train the model for hotel place prediction
model_place = RandomForestClassifier()
model_place.fit(X_train, y_place_train)

# Train the model for hotel price prediction
from sklearn.ensemble import RandomForestRegressor
model_price = RandomForestRegressor()
model_price.fit(X_train, y_price_train)

# Make predictions
y_name_pred = model_name.predict(X_test)
y_place_pred = model_place.predict(X_test)
y_price_pred = model_price.predict(X_test)

# Evaluating the model
print("Hotel Name Prediction Report:\n", classification_report(y_name_test, y_name_pred))
print("Hotel Place Prediction Report:\n", classification_report(y_place_test, y_place_pred))
print("Hotel Price Prediction Report:\n", mean_squared_error(y_price_test, y_price_pred))

Hotel Name Prediction Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       655
           1       1.00      1.00      1.00      1006
           2       1.00      1.00      1.00       894
           3       1.00      1.00      1.00       969
           4       1.00      1.00      1.00       841
           5       1.00      1.00      1.00       896
           6       1.00      1.00      1.00       997
           7       1.00      1.00      1.00      1025
           8       1.00      1.00      1.00       828

    accuracy                           1.00      8111
   macro avg       1.00      1.00      1.00      8111
weighted avg       1.00      1.00      1.00      8111

Hotel Place Prediction Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       828
           1       1.00      1.00      1.00       841
           2       1.00      1.00      1.00       896
           3       1.00      1.00      1.00       655
           4       1.00      1.00      1.00       969
           5       1.00      1.00      1.00       894
           6       1.00      1.00      1.00       997
           7       1.00      1.00      1.00      1025
           8       1.00      1.00      1.00      1006

    accuracy                           1.00      8111
   macro avg       1.00      1.00      1.00      8111
weighted avg       1.00      1.00      1.00      8111

Hotel Price Prediction Report:
 1.4727918486796593e-23

In [ ]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Sample data for fitting label encoder (ensure these cover all possible labels)
hotel_names = ['Hotel A', 'Hotel K', 'Hotel Z']
hotel_places = ['Florianopolis (SC)', 'Salvador (BH)', 'Aracaju (SE)']

# Initialize and fit the LabelEncoder for hotel names and places
label_encoder_name = LabelEncoder()
label_encoder_place = LabelEncoder()

label_encoder_name.fit(hotel_names)
label_encoder_place.fit(hotel_places)

# Example: Making a prediction
sample_data = pd.DataFrame({
    'travelCode': [0],
    'userCode': [0],
    'days': [4],
    'price': [313.02],
    'total': [1252.08]
})

# Assuming model_name, model_place, and model_price are already trained
predicted_name = model_name.predict(sample_data)
predicted_place = model_place.predict(sample_data)
predicted_price = model_price.predict(sample_data)

# Check if the predicted labels are within the range of the fitted labels
print(f"Predicted name index: {predicted_name[0]}")
print(f"Predicted place index: {predicted_place[0]}")

# Ensure the predictions are within the range of labels known to the encoder
if max(predicted_name) < len(label_encoder_name.classes_) and max(predicted_place) < len(label_encoder_place.classes_):
    # Inverse transform to get original labels
    print("Predicted Hotel Name:", label_encoder_name.inverse_transform(predicted_name))
    print("Predicted Hotel Place:", label_encoder_place.inverse_transform(predicted_place))
else:
    print("Error: Predicted labels are out of the known range of the encoder")

print("Predicted Hotel Price:", predicted_price)

Predicted name index: 0
Predicted place index: 3
Error: Predicted labels are out of the known range of the encoder
Predicted Hotel Price: [313.02]

In [ ]:
def predict_hotel(travelCode, userCode, days, price, total):
    sample_data = pd.DataFrame({
        'travelCode': [travelCode],
        'userCode': [userCode],
        'days': [days],
        'price': [price],
        'total': [total]
    })

    predicted_name = model_name.predict(sample_data)
    predicted_place = model_place.predict(sample_data)
    predicted_price = model_price.predict(sample_data)

    return {
        'name': label_encoder.inverse_transform(predicted_name)[0],
        'place': label_encoder.inverse_transform(predicted_place)[0],
        'price': predicted_price[0]
    }

# Example prediction
print(predict_hotel(0, 0, 4, 313.02, 1252.08))

{'name': 'Aracaju (SE)', 'place': 'Florianopolis (SC)', 'price': 313.020000000007}

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
import joblib
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Save the models and encoders to Google Drive
joblib.dump(model_name, 'model_name.joblib')
joblib.dump(model_place, 'model_place.joblib')
joblib.dump(model_price, 'model_price.joblib')
joblib.dump(label_encoder_name, 'label_encoder_name.joblib')
joblib.dump(label_encoder_place, 'label_encoder_place.joblib')

['/content/drive/My Drive/ML/Travel_capstone_project/Hotelpredict/label_encoder_place.joblib']